name: Continues deployment for service
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push Docker
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: darcigats/api
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploying new version
        uses: appleboy/ssh-action@master
        with:
          host: "67.205.164.114:22"
          username: "root"
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            /bin/bash /root/scripts/update.sh